name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build Runtime Library
        run: cd runtime && yarn build
      - name: Build Web Demo
        run: cd web-demo && yarn build
